### ISSUE TITLE
Need to run this project on MVC 5

### ISSUE THREAD

**Issue by ATabish90** [gordon-matt/Mosaico.NetCore#1]
Hi Gordon,

First of all, thank you so much for writing the back-end in .net for mosaico. Your project has really given me a hope of integrating drag and drop editor into my bulk mailing panel. 

Just need a little help here. I am using Visual Studio 2013 for the development environment and it is not supporting the .net core 2.0 hence I am not able to build and run your project directly. I have created new MVC 5 project and have pasted all the files in that. With little bit of changes here and there, I am even able to build and run the project successfully. Now there are certain things which I am still struggling with. 
Firstly, I have to remove async from all the methods of MoisacoController since it is not supported in .net framework 4.5. Also I have set the method type as ActionResult instead of IActionResult.
Secondly, Some of the method's return type is Ok() method which is also not supportable in my current project. So I have changed their datatype to JsonResult.

Now the thing is, I am able to run the index page even able to select and display the templates from there on the editor page and even able to upload images from my local machine but after successful upload, images are not displaying. 
This is my upload method.

` [Route("upload")]
        public JsonResult  Upload()
        {
            var files = Request.Files;
            var returnList = new List<MosaicoFileInfo>();

            foreach (string fileName in files)
            {
                HttpPostedFileBase file = Request.Files[fileName];
                if (file.ContentLength > 0)
                {
                    string _FileName = Path.GetFileName(file.FileName);
                    string _path = Path.Combine(Server.MapPath("~/Media/Uploads/"), _FileName);
                    string _thumb = Path.Combine(Server.MapPath("~/Media/Thumbs/"), _FileName);
                    file.SaveAs(_path);

                    try
                    {

                        var image = System.Drawing.Image.FromFile(_path);
                        var thumbnail = ImageHelper.Resize(image, 120, 90);
                        thumbnail.Save(_thumb);
                    }
                    catch (Exception) { }

                    returnList.Add(new MosaicoFileInfo
                    {
                        Name = file.FileName,
                        Size = file.ContentLength,
                        Type = System.Web.MimeMapping.GetMimeMapping(file.FileName),
                        Url = Path.Combine(Server.MapPath("~/Media/Uploads/"), _FileName),
                        ThumbnailUrl = Path.Combine(Server.MapPath("~/Media/Thumbs/"), _FileName),
                        DeleteUrl = string.Concat("/mosaico/img-delete/", file.FileName),
                        DeleteType = "DELETE"
                    });
                }
            }
            return Json(new { files = returnList });
            //return Ok(new { files = returnList });
        }`

After upload, Al though the files and thumbnails are getting uploaded, I am getting the below error

![image](https://user-images.githubusercontent.com/33214884/32361960-4c35f788-c08b-11e7-9472-57b9250592d7.png)

Is this because I am not returning Ok() method or is it something else? Can you please let me know what am I doing wrong. Should this project needs .net core features only to run or is there any work around possible to run it in my current project. 

Any kind of help would be much appreciated.

Thanks,
Tabish A

**Comment by gordon-matt** [comment]
Hi @ATabish90 . It sounds like you did the correct thing. Did you solve the problem yet? If not, please open the browser developer tools with F12 and look at the Console and Network tabs to see if there is any further info and paste it here for me to see.

**Comment by ATabish90** [comment]
Hi Gordon,

Sorry for such a late reply. 

This is what showing in the browser's console. I think both the "failed to load resource" error has nothing to do with the template images. 

![image](https://user-images.githubusercontent.com/33214884/33875129-3f5359c2-df47-11e7-8f2c-4a508e74522f.png)

Also need to add one thing, as I have mentioned earlier that OK(object) method is not working in my current MVC version so I have replaced it with Json(object). 

Instead of

public async Task<IActionResult> Upload()
{

            return OK(object)
}

I have mentioned 

 public JsonResult Upload()
{
             return Json(object)
}


Is this the reason for images not displaying properly. Is there any other alternate available for OK() method. Kindly let me know if possible.

**Comment by gordon-matt** [comment]
@ATabish90 No, I don't think changing `Ok()` to `Json()` would cause the problem. Is it possible for you to upload your project (or create a small example project) and put it on GitHub? Then give me the link.. I will try debug it for you and see where the problem is.

**Comment by ATabish90** [comment]
Hi Gordon,

Thanks a lot for helping me out on this. Kindly find the project on below repository.

https://github.com/ATabish90/mosaico_mvc5

**Comment by gordon-matt** [comment]
@ATabish90, I had some issues trying to get your demo working - there was an error message about missing files and what not. So instead of trying figure out what's wrong with your solution, I decided to create one from scratch myself. You can find it here: [Mosaico.Mvc5](https://github.com/gordon-matt/Mosaico.Mvc5). I haven't done a lot of testing on it, but it seems to be working fine.

**Comment by ATabish90** [comment]
Hi,

I am really grateful for your efforts Gordon. Thank you very much for this and extremely sorry for the inconvenience caused. This would help me to integrate drag and drop editor in our email marketing application.

I know I am asking for too much but is it possible for you to let me know about the initial data require to be stored in database. I am currently storing like this. 

![image](https://user-images.githubusercontent.com/33214884/34247414-65c4e428-e658-11e7-8711-07232e1406c3.png)

So whenever I click on on any template of the index page. I am getting an empty screen like this

![image](https://user-images.githubusercontent.com/33214884/34247725-89580cca-e659-11e7-881b-671e3fd9a165.png)

As soon as I changed the parameter ID to 0, the screen gets populated with the selected template's html

![image](https://user-images.githubusercontent.com/33214884/34247805-d29485b2-e659-11e7-884e-d3e274b482e2.png)

Am I doing something wrong here? Please let me know whenever you get time.

**Comment by gordon-matt** [comment]
I'm not sure why you are manually inputting records in the database... but I think you will find that the problem you are having is because the Metadata fields are blank and the Content fields are not valid. The Mosaico editor needs these 2 things when loading existing templates. The reason it's working when you put 0 for the ID is because it's creating a new template for you.. if you put anything other than 0, it will try load from the database, in which case yours is wrong.

If you just run the demo I created and click the "Mosaico" link in the menu, you will be taken to a page that shows you your existing templates and a "Create" button to create new ones. Just delete the entries from your database and start creating them from that demo page.

**Comment by ATabish90** [comment]
Hi Gordon,

Thank you so so much for helping me out on this project. I am really grateful to you Sir. This is one of the biggest hurdle in our development and your support has helped us greatly in overcoming this hurdle.

I will make sure not to disturb you again on this :)

Thanks again and Happy Holidays.
