### ISSUE TITLE
Could you assist please?

### ISSUE THREAD

**Issue by MarkTrippier** [gordon-matt/Mosaico.NetCore#3]
Hi,

This is not an issue, but a request for help, as I cannot see how to email you I am posting it here.

Sorry to be a royal pain in the ... but I am new to ASP.NET and C# and am struggling somewhat and was hoping you could help by pointing me in the right direction.

I have an appication in DotNetNuke CMS that creates and lists the data entries for "templates".  I am then using the mosaico editor that you provided the asp.net code for to allow the user to create or edit their own templates.  As a result of the table being used by DotNetNuke I only intend to use the editor functionality of the ASP.NET Core application.  As I do not understand how to get the ASP.NET application to share user creditentials with the DotNetNuke application, I am passing parameters to the editor model directly in the URL and not using the login functionality of the mosaico app.

I need to save uploads and thumbs etc . in a seperate folder for each user based upon their "SECID" passed in the URL string.  I then need to get the program to read the images from the dynamic folder.  This way each user is only seeing their own images.  I have created the folder from the editor route successfully, but can't work out of the reference the folder in the "uploads" routes or indeed in the relevant views.

I have pasted my code for the editor route below so you can see how I am creating the folder.  I am sure this is the wrong approach but at least it might help you see what I am trying to achieve.

//CODE

[Route("editor/{secid?}/{createuserid?}/{name}/{template}/{ContentID?}")]
        public async Task<IActionResult> Editor(string secid, int createuserid, string name, MosaicoTemplate template, string ContentID)
        {
            // CREATE FOLDERS FOR USER
            var foldername = secid;
            var uploadpath = @"wwwroot/Media/Uploads/";
            var thumbspath = @"wwwroot/Media/Thumbs/";
            System.IO.Directory.CreateDirectory(uploadpath + foldername);
            System.IO.Directory.CreateDirectory(thumbspath + foldername);

// END CODE

Any help you can offer on how I can achieve this level of user seperation for images would be very much appreciated.

Kind regards

Mark

**Comment by gordon-matt** [comment]
Hi there,

I have never used DNN, so I can't comment on the specifics, but it appears you basically want a separate folder for each user. Whether you use the "User" property on the Controller or get your unique user ID from elsewhere is up to you.. all you have to do is modify the appropriate URLs in `GetUploads()`, `Upload()`, etc to check for a specific subfolder for that current user.. it seems you already have the right idea, so I am not sure what you are asking for. The specific implementation is up to you really. Is there something I am misunderstanding?

**Comment by MarkTrippier** [comment]
Hi Matt,

Thank you very much for taking the time to reply.  Very much appreciated.

I think as you say I was on the right lines, just wasn’t sure how to modify the GetUploads(), Upload(), etc. or even find where the button that calls it is to modify what it passes to it.

I will have another look now that you have confirmed that I am on the right lines, but any suggestions / short cuts, would be greatly welcomed.

Many thanks

Mark
